### ISSUE TITLE
关于群聊的currentKey该如何制定，求教大神

### ISSUE THREAD

**Issue by PeterLocas** [im-js/im.js#18]
我现在有一个问题你那个手机端的currentkey是${payload.toAccount}-${payload.FromAccount}`;这样让聊天的列表和和聊天窗口对应的。现在我如果加上群聊的话，我不知道改如何这样对应关系了，求教！，群聊和单聊都通用

**Comment by plusmancn** [comment]
群聊一般会有 `groupKey` ，如果要添加群聊的话，建议用 `groupKey` 做关联。

**Comment by PeterLocas** [comment]
@plusmancn 嗯刚才用GroupID试了下，谢谢大神
