### ISSUE TITLE
您好 我想请教您个问题

### ISSUE THREAD

**Issue by 420697228** [im-js/im.js#3]
聊天界面的输入框键盘上完成按钮是怎么去掉的啊，我在ios上跑的，我也想把输入框放在键盘顶部，但是键盘上有个完成按钮，而且键盘收起时底输入框不会回到最底下。

**Comment by plusmancn** [comment]
如果要去掉的话，要改原生代码，RN 层面不支持。
RN 只能更改 `returnKeyType`，传送 [TextInput](https://facebook.github.io/react-native/docs/textinput.html)

键盘收缩看下 [KeyboardAvoidingView](https://facebook.github.io/react-native/docs/keyboardavoidingview.html) 模块

**Comment by 420697228** [comment]
好吧 谢谢啦
