### ISSUE TITLE
项目运行失败

### ISSUE THREAD

**Issue by ElvisVern** [im-js/im.js#5]
/Users/mao/Desktop/im.js/node_modules/react-native/React/Base/RCTPlatform.m:22:10: note: previous case defined here
    case UIUserInterfaceIdiomPad:
         ^
2 errors generated.

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/mao/Desktop/im.js/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTPlatform.o Base/RCTPlatform.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/ImClient.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ImClient.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

为什么会报这个错误呢

**Comment by plusmancn** [comment]
试试这个 https://github.com/facebook/react-native/issues/7308

**Comment by ElvisVern** [comment]
额。。我全都试过了  还是没解决  我升级xcode 8 试试  谢谢啊

**Comment by ElvisVern** [comment]
升级后运行成功。感谢楼主
