### ISSUE TITLE
登录成功后在哪里实现的跳转

### ISSUE THREAD

**Issue by yuanchuming** [im-js/im.js#6]
_login = async () => {
        try {
            await profileStore.login(
                this.state.name,
                this.state.phone
            );
            // toast
        } catch (e) {
            // toast
        }
    }

**Comment by plusmancn** [comment]
使用 `mobx` 做状态同步的，如果登录状态发生改变，重新触发组件渲染。

**Comment by yuanchuming** [comment]
看到了， 非常感谢！
