### ISSUE TITLE
 集成一个第三方推送服务

### ISSUE THREAD

**Issue by yuanchuming** [im-js/im.js#7]
socket.io  能不能实现推送 通知提醒 ？

**Comment by plusmancn** [comment]
@yuanchuming 
`socket.io` 能做到 app 激活状态下的推送。  
离线推送的话，`iOS` 要走 `APNs`，安卓要做后台保活，这就超越 RN 的讨论范围了。   
我记得 `jpush` 有专门针对 RN 的原生插件，你可以去看看

**Comment by yuanchuming** [comment]
@plusmancn  好的非常感谢！
